name: sub2api
services:
  postgres:
    image: postgres:18-alpine
    container_name: sub2api-postgres
    environment:
      - POSTGRES_USER=sub2api
      - POSTGRES_PASSWORD=daoshu123
      - POSTGRES_DB=sub2api
      - TZ=Asia/Shanghai
    networks:
      - sub2api-network
    ports:
      - "5432:5432"

  redis:
    image: redis:8-alpine
    container_name: sub2api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    networks:
      - sub2api-network


networks:
  sub2api-network:
    driver: bridge
